config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'videos', to: 'videos#index'
  get 'qiita_articles', to: 'qiita_articles#index'
  get 'zenn_articles', to: 'zenn_articles#index'


  #お問合せフォーム
  get 'contact', to: 'static_pages#contact'
  get 'privacy', to: 'static_pages#privacy'
  get 'terms', to: 'static_pages#terms'

  resources :profiles, only: %i[show edit update destroy]
  resources :users, only: %i[new create]
  resources :users do
    resources :bookmarks, only: [:index]
  end
  resources :bookmarks, only: [:create, :destroy]
  
  resources :shortcuts, only: %i[index]
  resources :password_resets, only: %i[new create edit update]
  resources :templates, only: %i[index new create destroy]

  #/google_login_api/callbackに来るPOSTリクエストをcallbackアクションで
  post '/google_login_api/callback', to: 'google_login_api#callback'

  #letter_opener_webにアクセスするために
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  #sitemapへのルーティング
  get '/sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/#{ENV['S3_BUCKET_NAME']}/sitemaps/sitemap.xml.gz")
end

app/views/templates/_form.html.erb
<div class="lg:w-1/2 md:w-2/3 mx-auto">
  <div class="flex flex-wrap -m-2">
  <%= form_with model: template, local: true do |f| %>
    <div class="p-2 w-2/3">
      <div class="relative">
        <%= f.label :name, class: "leading-7 text-sm text-gray-600" %>
        <%= f.text_field :name, class: "w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out" %>
      </div>
    </div>
    <div class="p-2 w-full">
      <div class="relative">
        <%= f.label :url, class: "leading-7 text-sm text-gray-600" %>
        <%= f.text_area :url, class: "w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 h-32 text-base outline-none text-gray-700 py-1 px-3 resize-none leading-6 transition-colors duration-200 ease-in-out" %>
      </div>
    </div>
    <div class="p-2 w-full">
      <%= f.submit '投稿', class: "flex mx-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg" %>
    </div>
  <% end %>
  </div>
</div>

app/views/templates/_template.html.erb
<tr>

  <td class="h-px w-px whitespace-nowrap">
    <div class="px-6 py-3">
      <span class="text-sm text-gray-600">
        <%= template.name %>
      </span>
    </div>
  </td>

    <td class="h-px w-px whitespace-nowrap">
    <div class="px-6 py-3">
      <span class="inline-flex items-center gap-1.5 py-0.5 px-2 rounded-full text-xs font-medium bg-green-100 text-green-800">
        <svg class="w-2.5 h-2.5" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
          <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
        </svg>
        Successful
      </span>
    </div>
  </td>


  <td class="h-px w-px whitespace-nowrap">
    <div class="px-6 py-3">
    <%= link_to template.url do %>
      <button type="button" class="inline-flex flex-shrink-0 justify-center items-center gap-x-2.5 py-2 px-2.5 rounded-md border font-medium bg-white text-gray-700 shadow-sm align-middle hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-gray-400 focus:ring-offset-2 focus:ring-offset-white transition-all text-xs">
        Let's check
        <svg class="h-3.5 w-3.5 text-gray-400" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
          <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/>
          <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>
        </svg>
      </button>
    <% end %>
    </div>
  </td>

  <td class="h-px w-px whitespace-nowrap">
    <div class="px-6 py-3">
    <%= link_to profile_path(template.user) do %>
      <div class="flex items-center gap-x-2">
        <% if template.user.avatar.attached? %>
          <%= image_tag template.user.avatar, class: "inline-block h-6 w-6 rounded-full" %>
        <% else %>
          <%= image_tag 'user_sample.png', class: "inline-block h-6 w-6 rounded-full" %>
        <% end %>
        <div class="grow">
          <span class="text-sm text-gray-600">
            <%= template.user.name %>
          </span>
        </div>
      </div>
      <% end %>
    </div>
  </td>

  <td class="h-px w-px whitespace-nowrap">
    <div class="px-6 py-3">
      <span class="text-sm text-gray-600">
        <%= l template.created_at, format: :short %>
      </span>
    </div>
  </td>

  <td class="h-px w-px whitespace-nowrap">
  <% if current_user.own?(template) %>
    <p class="text-red-600 text-sm"><%= link_to (t 'defaults.delete'), template_path(template), data: { turbo_method: :delete, turbo_confirm: '削除しますか？' } %></p>
  <% end %>
  </td>
</tr>

app/views/templates/index.html.erb
<!-- Table Section -->
<div class="max-w-[85rem] px-4 py-20 sm:px-6 lg:px-8 lg:py-14 mx-auto">
  <!-- Card -->
  <div class="flex flex-col">
    <div class="-m-1.5 overflow-x-auto">
      <div class="p-1.5 min-w-full inline-block align-middle">
        <div class="bg-white border border-gray-200 rounded-xl shadow-sm overflow-hidden">
          <!-- Header -->
          <div class="px-6 py-4 grid gap-3 md:flex md:justify-between md:items-center border-b border-gray-200">
            <div>
              <h2 class="text-xl font-semibold text-gray-800">
                テンプレート
              </h2>
              <p class="text-sm text-gray-600">
                テンプレートを投稿いただく際は<%= link_to 'こちら', 'https://www.notion.so/ja-jp/help/sharing-and-permissions', class: "inline-flex items-center gap-x-1.5 text-blue-600 decoration-2 hover:underline font-medium" %>の「Web上に公開する」をご一読ください。
              </p>
            </div>

            <div>
              <div class="inline-flex gap-x-2">
              <!--
                <a class="py-2 px-3 inline-flex justify-center items-center gap-2 rounded-md border font-medium bg-white text-gray-700 shadow-sm align-middle hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-white focus:ring-blue-600 transition-all text-sm" href="#">
                  View all
                </a>
                -->

                <%= link_to new_template_path, class: "py-2 px-3 inline-flex justify-center items-center gap-2 rounded-md border border-transparent font-semibold bg-blue-500 text-white hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 transition-all text-sm" do %>
                  <svg class="w-3 h-3" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" fill="none">
                    <path d="M2.63452 7.50001L13.6345 7.5M8.13452 13V2" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
                  </svg>
                  投稿
                <% end %>
              </div>
            </div>
          </div>
          <!-- End Header -->

          <!-- Table -->
          <table class="min-w-full divide-y divide-gray-200">
            <thead>
              <tr>

                <th scope="col" class="px-6 py-3 text-left">
                  <div class="flex items-center gap-x-2">
                    <span class="text-xs font-semibold uppercase tracking-wide text-gray-800">
                      Title
                    </span>
                  </div>
                </th>

                <th scope="col" class="px-6 py-3 text-left">
                  <div class="flex items-center gap-x-2">
                    <span class="text-xs font-semibold uppercase tracking-wide text-gray-800">
                      Kind
                    </span>
                  </div>
                </th>

                <th scope="col" class="px-6 py-3 text-left">
                  <div class="flex items-center gap-x-2">
                    <span class="text-xs font-semibold uppercase tracking-wide text-gray-800">
                      View
                    </span>
                  </div>
                </th>

                <th scope="col" class="px-6 py-3 text-left">
                  <div class="flex items-center gap-x-2">
                    <span class="text-xs font-semibold uppercase tracking-wide text-gray-800">
                      Contributor
                    </span>
                  </div>
                </th>

                <th scope="col" class="px-6 py-3 text-left">
                  <div class="flex items-center gap-x-2">
                    <span class="text-xs font-semibold uppercase tracking-wide text-gray-800">
                      Created
                    </span>
                  </div>
                </th>

                <th scope="col" class="px-6 py-3 text-right"></th>
              </tr>
            </thead>

            <tbody class="divide-y divide-gray-200">
              <%= render @templates %>
            </tbody>
          </table>
          <!-- End Table -->

          <!-- Footer -->
          <div class="px-6 py-4 grid gap-3 md:flex md:justify-between md:items-center border-t border-gray-200">
            <div>
              <p class="text-sm text-gray-600">
                <span class="font-semibold text-gray-800">
                  <%= @templates.count %>
                </span> results
              </p>
            </div>

            <div>
              <div class="inline-flex gap-x-2">
                <button type="button" class="py-2 px-3 inline-flex justify-center items-center gap-2 rounded-md border font-medium bg-white text-gray-700 shadow-sm align-middle hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-white focus:ring-blue-600 transition-all text-sm">
                  <svg class="w-3 h-3" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
                  </svg>
                  Prev
                </button>

                <button type="button" class="py-2 px-3 inline-flex justify-center items-center gap-2 rounded-md border font-medium bg-white text-gray-700 shadow-sm align-middle hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-white focus:ring-blue-600 transition-all text-sm">
                  Next
                  <svg class="w-3 h-3" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
                  </svg>
                </button>
              </div>
            </div>
          </div>
          <!-- End Footer -->
        </div>
      </div>
    </div>
  </div>
  <!-- End Card -->
</div>
<!-- End Table Section -->

app/views/templates/new.html.erb
<section class="text-gray-600 body-font relative">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-12">
      <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">
          投稿
          <img src="https://file.notion.so/f/s/03e8fadf-f1a1-4373-8040-a10093e540b2/notion-logo.svg?id=afd237b0-8678-4b9e-87ef-cbcdf5b5dab5&table=block&spaceId=e12b42ac-4e54-476f-a4f5-7d6bdb1e61e2&expirationTimestamp=1686921282132&signature=6hYdgzRom0FQof6lTdt5KKXSvLV9BSAJkCXQx5t4Z9s&downloadName=notion-logo.svg" class="inline-block h-8 w-8">
        </h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">テンプレート投稿してくださりありがとうございます！<p>
    </div>
    <%= render 'form', { template: @template } %>
  </div>
</section>