config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'videos', to: 'videos#index'
  get 'qiita_articles', to: 'qiita_articles#index'
  get 'zenn_articles', to: 'zenn_articles#index'


  #お問合せフォーム
  get 'contact', to: 'static_pages#contact'
  get 'privacy', to: 'static_pages#privacy'
  get 'terms', to: 'static_pages#terms'

  resources :profiles, only: %i[show edit update destroy]
  resources :users, only: %i[new create]
  resources :users do
    resources :bookmarks, only: [:index]
  end
  resources :bookmarks, only: [:create, :destroy]
  
  resources :shortcuts, only: %i[index]
  resources :password_resets, only: %i[new create edit update]
  resources :templates, only: %i[index new create destroy]

  #/google_login_api/callbackに来るPOSTリクエストをcallbackアクションで
  post '/google_login_api/callback', to: 'google_login_api#callback'

  #letter_opener_webにアクセスするために
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  #sitemapへのルーティング
  get '/sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/#{ENV['S3_BUCKET_NAME']}/sitemaps/sitemap.xml.gz")
end

app/views/shared/_before_login_header.html.erb
<header class="text-gray-600 body-font bg-white">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <%= link_to root_path, class: "flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0" do %>
      <%= image_tag('logo.png', class: "w-10 h-10 text-white p-2 rounded-full") %>

      <span class="ml-3 text-xl"><%= (t 'defaults.be_notioner') %></span>
    <% end %>

    <nav class="md:ml-auto md:mr-auto flex flex-wrap items-center text-base justify-center">
      <%= link_to (t 'defaults.shortcut'), shortcuts_path, class: "mr-5 btn btn-ghost hover:text-gray-900" %>
      <%= link_to (t 'defaults.templates'), templates_path, class: "mr-5 btn btn-ghost hover:text-gray-900" %>
      <div class="dropdown dropdown-end">
        <label tabindex="0" class="btn btn-ghost m-1"><%= (t 'defaults.articles') %></label>
        <ul tabindex="0" class="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52">
          <li>
            <%= link_to videos_path, class: "link link-hover" do %>
              <%= image_tag 'yt_icon_rgb.png', class: "inline-block h-6 w-6" %>Youtube
            <% end %>
          </li>
          <li>
            <%= link_to qiita_articles_path, class: "link link-hover" do %>
              <%= image_tag 'qiita.png', class: "inline-block h-6 w-6" %>Qiita
            <% end %>
          </li>
          <li>
            <%= link_to zenn_articles_path, class: "link link-hover" do %>
              <%= image_tag 'zenn.png', class: "inline-block h-6 w-6" %>Zenn
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
    <%= link_to (t 'defaults.login'), login_path, class: "btn btn-ghost" %>
  </div>
</header>

app/views/shared/_bookmark.html.erb
<%= form_with url: bookmarks_path, method: :post, local: true do |form| %>
  <%= form.hidden_field :bookmarkable_type, value: bookmarkable.class.name %>
  <%= form.hidden_field :bookmarkable_id, value: bookmarkable.id %>
  <%= form.button type: 'submit' do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 011.186 0z"></path>
    </svg>
  <% end %>
<% end %>

app/views/shared/_bookmark_button.html.erb
<% if current_user.bookmarked?(bookmarkable) %>
  <%= render 'shared/unbookmark', bookmarkable: bookmarkable %>
<% else %>
  <%= render 'shared/bookmark', bookmarkable: bookmarkable %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <% case key %>
  <% when "success" %>
    <div class="alert alert-success shadow-lg">
      <div>
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
        <span>
          <%= value %>
        </span>
      </div>
    </div>
    <% when "danger" %>
      <div class="alert alert-error shadow-lg">
        <div>
          <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
          <span>
            <%= value %>
          </span>
        </div>
      </div>
    <% when "info" %>
      <div class="alert alert-info shadow-lg">
        <div>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="stroke-current flex-shrink-0 w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
          <span>
            <%= value %>
          </span>
        </div>
      </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer footer-center p-10 bg-stone-200 text-base-content rounded">
  <div class="grid grid-flow-col gap-4">
    <%= link_to (t 'defaults.terms'), terms_path, class: "link link-hover" %>
    <%= link_to (t 'defaults.privacy'), privacy_path, class: "link link-hover" %>
    <%= link_to (t 'defaults.contact'), 'https://docs.google.com/forms/d/e/1FAIpQLSfG0pMfLg41F2wvvvKMiY8Nga7g-rz-qR98HgfcIXdKa4xWHw/viewform?usp=sf_link', class: "link link-hover" %>
  </div> 
  <div>
    <div class="grid grid-flow-col gap-4">
      <%= link_to 'https://twitter.com/home' do %>
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-current">
          <path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path>
        </svg>
      <% end %>

      <%= link_to 'https://github.com/reckyy/Be_Notioner' do %>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="24" height="24" class="fill-current">
          <path d="M8 0c4.42 0 8 3.58 8 8a8.013 8.013 0 0 1-5.45 7.59c-.4.08-.55-.17-.55-.38 0-.27.01-1.13.01-2.2 0-.75-.25-1.23-.54-1.48 1.78-.2 3.65-.88 3.65-3.95 0-.88-.31-1.59-.82-2.15.08-.2.36-1.02-.08-2.12 0 0-.67-.22-2.2.82-.64-.18-1.32-.27-2-.27-.68 0-1.36.09-2 .27-1.53-1.03-2.2-.82-2.2-.82-.44 1.1-.16 1.92-.08 2.12-.51.56-.82 1.28-.82 2.15 0 3.06 1.86 3.75 3.64 3.95-.23.2-.44.55-.51 1.07-.46.21-1.61.55-2.33-.66-.15-.24-.6-.83-1.23-.82-.67.01-.27.38.01.53.34.19.73.9.82 1.13.16.45.68 1.31 2.69.94 0 .67.01 1.3.01 1.49 0 .21-.15.45-.55.38A7.995 7.995 0 0 1 0 8c0-4.42 3.58-8 8-8Z"></path>
        </svg>
      <% end %>
    </div>
  </div> 

  <div>
    <p>
      © 2023 - All rights reserved by recky.
    </p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="text-gray-600 body-font bg-white">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <%= link_to root_path, class: "flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0" do %>
      <%= image_tag('logo.png', class: "w-10 h-10 text-white p-2 rounded-full") %>

      <span class="ml-3 text-xl"><%= (t 'defaults.be_notioner') %></span>
    <% end %>

    <nav class="md:ml-auto md:mr-auto flex flex-wrap items-center text-base justify-center">
      <%= link_to (t 'defaults.shortcut'), shortcuts_path, class: "mr-5 btn btn-ghost hover:text-gray-900" %>
      <%= link_to (t 'defaults.templates'), templates_path, class: "mr-5 btn btn-ghost hover:text-gray-900" %>
      <div class="dropdown dropdown-end">
        <label tabindex="0" class="btn btn-ghost m-1"><%= (t 'defaults.articles') %></label>
        <ul tabindex="0" class="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52">
          <li>
            <%= link_to videos_path, class: "link link-hover" do %>
              <%= image_tag 'yt_icon_rgb.png', class: "inline-block h-6 w-6" %>Youtube
            <% end %>
          </li>
          <li>
            <%= link_to qiita_articles_path, class: "link link-hover" do %>
              <%= image_tag 'qiita.png', class: "inline-block h-6 w-6" %>Qiita
            <% end %>
          </li>
          <li>
            <%= link_to zenn_articles_path, class: "link link-hover" do %>
              <%= image_tag 'zenn.png', class: "inline-block h-6 w-6" %>Zenn
            <% end %>
          </li>
        </ul>
      </div>
    </nav>

    <div class="flex-none gap-2">
      <div class="dropdown dropdown-end">
        <label tabindex="0" class="btn btn-ghost btn-circle avatar" id="header-avatar">
          <div class="w-10 rounded-full">
            <% if current_user.avatar.attached? %>
              <%= image_tag current_user.avatar %>
            <% else %>
              <%= image_tag('user_sample.png', size: "200x200") %>
            <% end %>
          </div>
        </label>
        <ul tabindex="0" class="mt-3 p-2 shadow menu menu-compact dropdown-content bg-base-100 rounded-box w-52 text-base-content">
          <li><%= link_to (t 'defaults.profile'), profile_path(current_user) %></li>
          <li><%= link_to "ブックマークした記事", user_bookmarks_path(current_user) %></li>
          <li><%= link_to (t 'defaults.logout'), logout_path, data: { turbo_method: :delete } %></li>
          <li class="text-red-600"><%= link_to (t 'defaults.quit'), profile_path(current_user.id), data: { turbo_method: :delete, turbo_confirm: '本当に退会しますか？' } %></li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/shared/_unbookmark.html.erb
<%= form_with url: bookmark_path(bookmarkable), method: :delete, local: true do |form| %>
  <%= form.hidden_field :bookmarkable_type, value: bookmarkable.class.name %>
  <%= form.hidden_field :bookmarkable_id, value: bookmarkable.id %>
  <%= form.button type: 'submit' do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 011.186 0z"></path>
    </svg>
  <% end %>
<% end %>