config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'videos', to: 'videos#index'
  get 'qiita_articles', to: 'qiita_articles#index'
  get 'zenn_articles', to: 'zenn_articles#index'


  #お問合せフォーム
  get 'contact', to: 'static_pages#contact'
  get 'privacy', to: 'static_pages#privacy'
  get 'terms', to: 'static_pages#terms'

  resources :profiles, only: %i[show edit update destroy]
  resources :users, only: %i[new create]
  resources :users do
    resources :bookmarks, only: [:index]
  end
  resources :bookmarks, only: [:create, :destroy]
  
  resources :shortcuts, only: %i[index]
  resources :password_resets, only: %i[new create edit update]
  resources :templates, only: %i[index new create destroy]

  #/google_login_api/callbackに来るPOSTリクエストをcallbackアクションで
  post '/google_login_api/callback', to: 'google_login_api#callback'

  #letter_opener_webにアクセスするために
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  #sitemapへのルーティング
  get '/sitemap', to: redirect("https://s3-ap-northeast-1.amazonaws.com/#{ENV['S3_BUCKET_NAME']}/sitemaps/sitemap.xml.gz")
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to root_path, success: (t '.success')
    else
      flash.now[:danger] = (t '.danger')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other, success: (t '.success')
  end
end

app/views/user_sessions/new.html.erb
<div class="py-6 sm:py-8 lg:py-12">

<script src="https://accounts.google.com/gsi/client" async defer></script>

  <div class="mx-auto max-w-screen-2xl px-4 md:px-8">
    <h2 class="mb-4 text-center text-2xl font-bold text-gray-800 md:mb-8 lg:text-3xl"><%= (t 'defaults.login') %></h2>

    <div class="mx-auto max-w-lg rounded-lg border">

      <%= form_with url: login_path, local: true do |f| %>
      <div class="flex flex-col gap-4 p-4 md:p-8">
        <div>
          <%= f.label :email, User.human_attribute_name(:email), class: "mb-2 inline-lock text-sm text-gray-800 sm:text-base" %>
          <%= f.email_field :email, class: "w-full rounded border bg-gray-50 px-3 py-2 text-gray-800 outline-none ring-indigo-300 transition duration-100 focus:ring" %>
        </div>

        <div>
          <%= f.label :password, User.human_attribute_name(:password), class: "mb-2 inline-block text-sm text-gray-800 sm:text-base" %>
          <%= f.password_field :password, class: "w-full rounded border bg-gray-50 px-3 py-2 text-gray-800 outline-none ring-indigo-300 transition duration-100 focus:ring" %>
        </div>

        <%= f.submit (t '.login'), class: "btn block rounded-lg bg-gray-800 px-8 py-3 text-center text-sm font-semibold text-white outline-none ring-gray-300 transition duration-100 hover:bg-gray-700 focus-visible:ring active:bg-gray-600 md:text-base" %>

      <% end %>

        <div class="relative flex items-center justify-center">
          <span class="absolute inset-x-0 h-px bg-gray-300"></span>
          <span class="relative bg-white px-4 text-sm text-gray-400">
            <%= (t 'defaults.social_login') %>
          </span>
        </div>

        <div class="relative flex items-center justify-center">
        <div id="g_id_onload"
            data-client_id="<%= ENV['DATA_CLIENT_ID'] %>"
            data-context="signin"
            data-ux_mode="popup"
            data-login_uri="https://be-notioner.com/google_login_api/callback"
            data-auto_prompt="false">
        </div>

        <div class="g_id_signin"
            data-type="standard"
            data-shape="rectangular"
            data-theme="outline"
            data-text="signin_with"
            data-size="large"
            data-logo_alignment="center"
            data-width="400">
        </div>
        </div>

      </div>

      <div class="flex flex-col items-center justify-center bg-gray-100 p-4">
        <p class="text-center text-sm text-gray-500"><%= (t 'defaults.non_registered') %>&nbsp;
          <%= link_to (t 'defaults.sign_up'), new_user_path, class: "text-indigo-500 transition duration-100 hover:text-indigo-600 active:text-indigo-700 text-center text-sm" %>
        </p> <!-- &nbsp;は半角スペース -->

        <p class="text-center text-sm text-gray-500">パスワードをお忘れの方は&nbsp;
          <%= link_to "こちら", new_password_reset_path, class: "text-indigo-500 transition duration-100 hover:text-indigo-600 active:text-indigo-700 text-center text-sm" %>
        </p> 

      </div>
    </div>
  </div>
</div>